version: "3"
services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
    restart: always
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d:ro
    depends_on:
      - api-server
  api-server:
    image: tecobrary/tecobrary-api-server
    container_name: api-server
    restart: always
    depends_on:
      - mysql-db
    links:
      - mysql-db
    expose:
      - 9090